services:
  - type: web
    name: vitqa
    env: docker
    plan: free
    envVars:
      - key: JWT_SECRET
        generateValue: true
      - key: USDT_WALLET
        value: TBjQRf2DY1Vxi9yrvKYhifumcuz8rUrcwm
